---
title: "Avaliação do estado nutricional de crianças com epilepsias"
subtitle: "Análise dos pacientes - Modelo Binomial"
lang: pt
author: "Jaqueline Lamas da Silva"
knitr:
    opts_chunk: 
      fig.align: 'center'
format: 
  html:
    self-contained-math: true
    embed-resources: true
    code-fold: true
toc: true
editor: source
---

```{r, echo=FALSE, warning=FALSE}
rm(list = ls(all = TRUE))
suppressMessages(library("dplyr"))
suppressMessages(library("MASS"))
suppressMessages(library("readr"))
suppressMessages(library("ggplot2"))
suppressMessages(library("tidyverse"))


library("kableExtra")

# Funções de MLG
source("C:/ufjf/2024.3/MlG/MLG/Funcoes/envelope.R")
source("C:/ufjf/2024.3/MlG/MLG/Funcoes/StepBackwardF.R")

# Dados
source("dados.R")


op<-par()
par<-par(pch=19)
cores<-c("#BAF3DE","#C9E69E","#FFC29A","#FF9B95")

# FUNCOES
selecaoModeloBinomial<-function(dados, modelo, ligacao, step="AIC")
{
  n<-nrow(dados)
  fit1<-try(switch(ligacao,
                logit = glm(modelo, family=binomial(logit)),
                probit = glm(modelo, family=binomial(link=probit)),
                cauchit = glm(modelo, family=binomial(link=cauchit)),
                log = glm(modelo, family=binomial(link=log)),
                cloglog = glm(modelo, family=binomial(link=cloglog)),
                stop("Link não reconhecido")), silent = T)
  summary(fit1)
  
  aux<-sum(class(fit1) != "try-error")
  if(step=="JAQ")
  {
    fit<-try(stepJAQ(fit1, trace = 0), silent = T)
  }else{
    fit<-try(stepAIC(fit1, trace = 0), silent = T)

  }
  aux2<-sum(class(fit) != "try-error")
  if( aux!=0  && aux2!=0 )
  {
    fit.model<-fit
  }else{
     fit.model<-0
  }
  return(fit.model)
}

ResultadosBinom<-function(dados, modelo, ligacao, tipo, alfa=0.05, step="AIC")
{
  n<-nrow(dados)
  familia<-paste0("Binomial-Link(",ligacao,")")
  print(familia)
  fits<-selecaoModeloBinomial(dados, modelo, ligacao, step)
  if(is.numeric(fits))
  {
    bic<-NA
    qualidade<-"Não Rodou"
    modelo.s<-"-----"

  }else{
         bic<-as.numeric(round(AIC(fits,k=log(n)),6))
         modelo.s<-deparse(formula(fits))
         teste<-try(envelope(fits,tipo), silent=T)
         aux<-sum(class(teste) != "try-error")
        if(aux==0)
        {
            qualidade<-"Não Rodou"
       }else{
              qualidade<-teste[[1]]
            }
  }
  return(data.frame(Family=familia,
                      QQplot=qualidade,
                      BIC=bic,
                      Modelo=modelo.s))
  
}


residuos<-function(fit.model, dados)
{

  X <- model.matrix(fit.model)
  V <- fitted(fit.model)  # no Binomial, sao as proporcoes estimadas
  Vm <- diag(V)
  w <- fit.model$weights  # vetor de pesos
  W <- diag(w)
  H1 <- solve(t(X)%*%W%*%X)
  H <- sqrt(W)%*%X%*%H1%*%t(X)%*%sqrt(W)
  hii <- diag(H)  # vetor diagonal de H


  # Resíduos
  rD <- resid(fit.model, type= "deviance")
  fi<-summary(fit.model)$dispersion
  tD <- rD*sqrt(fi/(1-hii))   # residuo deviance padronizado
  rp1 <- resid(fit.model, type= "pearson")
  rP <- as.numeric(sqrt(fi)*rp1)
  tS <- rP/sqrt(V*(1 - hii))  # Residuo padronizado
  
  # LDi
  LD = hii*(tS^2)/(1-hii) # pode falhar de pi_i<0.1 ou pi_i>0.9. Neste caso, fazer  Ldi x pi_i
  plot(tD, main="Resíduo")
  plot(V,tD, main="Resíduo x Ajustado", xlab="Ajustado")
  return(list(tD=tD, tS=tS, hii=hii, V=V, LD=LD))
}

```

## Adequação da porção diária de legumes e verduras
```{r}
attach(analise2.new)
#------------------------------------- Modelo  logístico-----------------------------
analise2.new$adeq_porcoes_dia_verduras_legumes<-factor(analise2.new$adeq_porcoes_dia_verduras_legumes, levels=c("A","I"))
Y<-adeq_porcoes_dia_verduras_legumes
modelo<-Y ~ di + dificuldade_motora  + constipacao  + sexo

fit<-glm(modelo, family = binomial(link = "logit"))
envelope(fit,"envel_bino_logit")
summary(fit)

# Resíduos

modelo.completo<-Y~tea+di+tdah+dificuldade_motora+disfagia+epilepsia_farmacorressistente+tipo_focal_generalizada+rec_vomito_diarreia+constipacao+etiologia+paralisia_cerebral+atraso_desenvolvimento_sn+idade_atual_anos+sexo


selecaoModeloBinomial<-function(dados, modelo, ligacao, step="AIC")
{
  n<-nrow(dados)
  fit1<-try(switch(ligacao,
                   logit = glm(modelo, family=binomial(logit)),
                   probit = glm(modelo, family=binomial(link=probit)),
                   cauchit = glm(modelo, family=binomial(link=cauchit)),
                   log = glm(modelo, family=binomial(link=log)),
                   cloglog = glm(modelo, family=binomial(link=cloglog)),
                   stop("Link não reconhecido")), silent = T)
  summary(fit1)
  
  aux<-sum(class(fit1) != "try-error")
  if(step=="JAQ")
  {
    fit<-try(stepJAQ(fit1, trace = 0), silent = T)
  }else{
    fit<-try(stepAIC(fit1, trace = 0), silent = T)
    
  }
  aux2<-sum(class(fit) != "try-error")
  if( aux!=0  && aux2!=0 )
  {
    fit.model<-fit
  }else{
    fit.model<-0
  }
  return(fit.model)
}

ResultadosBinom<-function(dados, modelo, ligacao, tipo, alfa=0.05, step="AIC")
{
  n<-nrow(dados)
  familia<-paste0("Binomial-Link(",ligacao,")")
  print(familia)
  fits<-selecaoModeloBinomial(dados, modelo, ligacao, step)
  if(is.numeric(fits))
  {
    bic<-NA
    qualidade<-"Não Rodou"
    modelo.s<-"-----"
    
  }else{
    bic<-as.numeric(round(AIC(fits,k=log(n)),6))
    modelo.s<-deparse(formula(fits))
    teste<-try(envelope(fits,tipo), silent=T)
    aux<-sum(class(teste) != "try-error")
    if(aux==0)
    {
      qualidade<-"Não Rodou"
    }else{
      qualidade<-teste[[1]]
    }
  }
  return(data.frame(Family=familia,
                    QQplot=qualidade,
                    BIC=bic,
                    Modelo=modelo.s))
  
}


residuos<-function(fit.model, dados)
{
  
  X <- model.matrix(fit.model)
  V <- fitted(fit.model)  # no Binomial, sao as proporcoes estimadas
  Vm <- diag(V)
  w <- fit.model$weights  # vetor de pesos
  W <- diag(w)
  H1 <- solve(t(X)%*%W%*%X)
  H <- sqrt(W)%*%X%*%H1%*%t(X)%*%sqrt(W)
  hii <- diag(H)  # vetor diagonal de H
  
  
  # Resíduos
  rD <- resid(fit.model, type= "deviance")
  fi<-summary(fit.model)$dispersion
  tD <- rD*sqrt(fi/(1-hii))   # residuo deviance padronizado
  rp1 <- resid(fit.model, type= "pearson")
  rP <- as.numeric(sqrt(fi)*rp1)
  tS <- rP/sqrt(V*(1 - hii))  # Residuo padronizado
  
  # LDi
  LD = hii*(tS^2)/(1-hii) # pode falhar de pi_i<0.1 ou pi_i>0.9. Neste caso, fazer  Ldi x pi_i
  plot(tD, main="Resíduo")
  plot(V,tD, main="Resíduo x Ajustado", xlab="Ajustado")
  return(list(tD=tD, tS=tS, hii=hii, V=V, LD=LD))
}

ResultadosBinom(analise2.new, modelo.completo, ligacao = "logit", tipo ="envel_bino_logit", step = "JAQ", alfa=0.05)

modelo.selecionado<-Y ~ tea + di + tdah + dificuldade_motora + tipo_focal_generalizada + constipacao + etiologia + idade_atual_anos + sexo
fit.selecionado<-glm(modelo.selecionado, family=binomial(link="logit"))
summary(fit.selecionado)


T2<-chisq.test(table(tea, Y), correct = F)
T3<-chisq.test(table(di, Y), correct = F)
T4<-chisq.test(table(constipacao, Y), correct = F)
T5<-chisq.test(table(dificuldade_motora, Y), correct = F)


modelo.selecionado<-Y ~ tea + di  + constipacao  + idade_atual_anos 
fit.selecionado<-glm(modelo.selecionado, family=binomial(link="logit"))
summary(fit.selecionado)

residuos(fit.selecionado, analise2.new)

```


```{r}
modelo.selecionado<-Y ~ di + tdah + dificuldade_motora + tipo_focal_generalizada + constipacao+ etiologia + idade_atual_anos + sexo

fit.selecionado<-glm(modelo.selecionado, family = binomial(link="logit"))
summary(fit.selecionado)

modelo<-Y ~   constipacao  + sexo
fit<-glm(modelo, family = binomial(link = "logit"))
summary(fit)
```


